### ISSUE TITLE
Kinship command is different in french

### ISSUE THREAD

**Issue by mydnic** [gjpc/CombatAnalysis#17]
here : https://github.com/gjpc/CombatAnalysis/blob/master/Locale/fr.lua#L401
the command to start talking to the kinship in the french client has changed to /k (like in the english client) instead of /conf

I can't submit a PR because it's changing the file encoding format :(

**Comment by gjpc** [comment]
Well @mydnic a year later and I committed your change. Please confirm it works and I'll post a new version to Lotro Interface

**Comment by mydnic** [comment]
Yup I just tried it again in my local files, changes "conf" to "k" then loaded the game and tried to share to kinship, works fine :)

**Comment by gjpc** [comment]
Thanks for the heads up. I have the fix all set in git I'll do an small update in LotroInterface
